# /etc/nftables.d/nsbox-nat.conf

# Динамический NAT для любого трафика, выходящего из сетевого моста nsbox
table ip nat {
    chain POSTROUTING {
        type nat hook postrouting priority srcnat; policy accept;
        
        # Включаем маскарадинг для любого трафика, который пришел с моста nsboxbr0
        # и уходит во внешний мир (на любой интерфейс, кроме самого моста)
        iifname "nsboxbr0" oifname != "nsboxbr0" masquerade
    }
}

# Разрешение пересылки пакетов (FORWARD) мимо блокировок Docker/Libvirt
table ip filter {
    chain FORWARD {
        type filter hook forward priority filter; policy accept;
        
        # Безоговорочно выпускаем трафик из сети контейнеров наружу
        iifname "nsboxbr0" accept
        
        # Разрешаем отвечать контейнерам на их запросы из внешнего мира
        oifname "nsboxbr0" ct state established,related accept
    }
}
