#!/bin/sh

set -eu

NSPAWN_DIR="/etc/systemd/nspawn"  # Каталог для конфигурационных файлов
TEMPLATES_DIR="/usr/share/nsbox"  # Каталог для шаблонов конфига и скрипта запуска
STORAGE_DIR="/var/lib/nsbox"      # Хранилище с развернутыми образами оверлеев 
MACHINES_DIR="/var/lib/machines"  # Стандартный путь machinectl

# Перезапуск от root, если скрипт запущен от обычного пользователя
# if [ "$(id -u)" -ne 0 ]; then
#     exec sudo "$0" "$@"
# fi

usage() {
    cat << EOF
Использование: $(basename "$0") <команда> [АРГУМЕНТЫ...]

$(basename "$0") — это легковесный инструмент для управления контейнерами systemd-nspawn 

Команды:
  images                 Вывести список образов контейнеров
  list                   Вывести список запущенных контейнеров и юнитов
  load  <image[:tag]>    Загрузить образ с dockerhub или из <image>, если это архив
  create <container>     Создать контейнер
  save  <container>      Сохранить образ в <container>.tar.gz
  start <container>      Запустить контейнер
  stop  <container>      Остановить контейнер
  restart <container>    Перезапустить контейнер
  exec <container> [cmd] Выполнить cmd в контейнере (по умолчанию /bin/sh)
  status <container>     Вывести статус контейнера и юнита
  log <container>        Вывести логи службы контейнера
  config <container>     Открыть файл конфигурации контейнера
  remove <container>     Удалить образ контейнера
  --help                 Показать эту справку и выйти
EOF
    exit 1
}

images() {
    machinectl list-images
}

list() {
    machinectl --full list 2>/dev/null
    echo ""
    # Если не нужно выводить легенду, добавить --no-legend
    systemctl list-units "nsbox@*" --all --no-pager
}

load() {
    image_ref=$1
    # Разбиение имени образа по двоеточию на имя и тег (если указан)
    image="${image_ref%%:*}"
    tag="${image_ref#*:}"
    [ "$image" = "$tag" ] && tag="latest"

    # Если $image указывает на файл попытка распаковать его в корень контейнера
    if [ -f "$image" ]; then
        image_file=$(basename "$image")
        container_name=$(echo "${image_file%%.tar*}" | sed 's/[^a-zA-Z0-9.-]/-/g')
        container_name="${container_name:0:64}"
        nspawn_file="${NSPAWN_DIR}/${container_name}.nspawn"

        # Определение корня контейнера по наличию каталога upper в архиве
        if tar -tf "$image" | grep -Eq '^(\./)?upper/$'; then
            root_dir="${STORAGE_DIR}/${container_name}"
        else
            root_dir="${MACHINES_DIR}/${container_name}"
        fi

        mkdir -p "$root_dir"
        tar -xf "$image" -C "$root_dir" || { rmdir "$root_dir"; exit 1; }
        
        # Создание корня контейнера
        mkdir -p "${MACHINES_DIR}/${container_name}"

        # Восстановление или создание нового конфига контейнера
        if [ -f "${root_dir}/${container_name}.nspawn" ]; then
            cp -i "${root_dir}/${container_name}.nspawn" "$NSPAWN_DIR"
            rm "${root_dir}/${container_name}.nspawn"
        else
            cp -n "${TEMPLATES_DIR}/config.tmpl" "$nspawn_file" 2>/dev/null || true
        fi

        exit 0
    fi

    container_name=$(echo "$image" | tr '/' '-')
    nspawn_file="${NSPAWN_DIR}/${container_name}.nspawn"
    root_dir="${MACHINES_DIR}/${container_name}"
    temp_dir=$(mktemp -d /var/tmp/nspawn.XXXXXX)

    if [ -d "$root_dir" ]; then
        read -p "Каталог $root_dir существует, распаковать поверх? [y/N]: " response
        [[ "$response" != [yY] ]] && exit 0
    fi

    # Скачивание docker-образа и распаковка в корень контейнера
    skopeo --insecure-policy copy docker://"${image}:${tag}" oci:"${temp_dir}:${tag}"
    config_json=$(skopeo inspect --config "oci:${temp_dir}:${tag}")
    umoci raw unpack --image "${temp_dir}:${tag}" "$root_dir"
    rm -rf "$temp_dir"

    # Извлечение команды, рабочей директории и пользователя из конфига образа 
    cmd=$(echo "$config_json" | jq -r '((.config.Entrypoint // []) + (.config.Cmd // [])) | join(" ")')
    cmd=${cmd:-/bin/sh}
    workdir=$(echo "$config_json" | jq -r '.config.WorkingDir // "/"')
    user=$(echo "$config_json" | jq -r '.config.User // ""')

    # Формирование строки Environment=KEY=VAL
    env_lines=$(echo "$config_json" | jq -r '
      .config.Env // [] | map("Environment=" + .) | join("\n")
    ')

    # Запись параметров в конец конфига .nspawn
    cp -n "${TEMPLATES_DIR}/config.tmpl" "$nspawn_file" 2>/dev/null || true
    echo "# Auto-generated parameters from OCI Image Config" >> "$nspawn_file"
    echo "Parameters=$cmd" >> "$nspawn_file"
    echo "WorkingDirectory=$workdir" >> "$nspawn_file"
    echo "$env_lines" >> "$nspawn_file"
}

create() {
    echo "$container_name" | grep -Eq '^[a-zA-Z0-9]+([.-][a-zA-Z0-9]+)*$' || { echo "Ошибка. Недопустимое имя контейнера"; exit 1; }
    # Создание корня образа
    sudo mkdir -p "${MACHINES_DIR}/${container_name}"
    # Создание файла конфигурации
    nspawn_file="${NSPAWN_DIR}/${container_name}.nspawn"
    sudo cp -n "${TEMPLATES_DIR}/config.tmpl" "$nspawn_file" || true
    sudo chgrp nsbox "$nspawn_file"
    sudo chmod 664 "$nspawn_file"
    # Раскомментирование параметра с командой запуска
    # sed -i "s/^ *# *Parameters/Parameters/" "$nspawn_file"
}

save() {
    if machinectl show "$container_name" >/dev/null 2>&1; then
        echo "Ошибка: Контейнер '${container_name}' запущен, остановите перед сохранением" >&2
        exit 1
    fi

    # Определение каталога, подлежащего архивированию
    if [ -d "${STORAGE_DIR}/${container_name}" ]; then
        root_dir="${STORAGE_DIR}/${container_name}"
    elif [ -d "${MACHINES_DIR}/${container_name}" ]; then
        root_dir="${MACHINES_DIR}/${container_name}"
    fi

    if [ -n "$root_dir" ]; then
        cp "${NSPAWN_DIR}/${container_name}.nspawn" "$root_dir" || true
        tar -czf "${container_name}.tar.gz" -C "$root_dir" .
        rm "$root_dir/${container_name}.nspawn" || true
    fi
}

start() {
    if machinectl show "$container_name" >/dev/null 2>&1; then
        echo "Контейнер '${container_name}' уже запущен"
        return 0
    fi

    if ! machinectl image-status "$container_name" >/dev/null 2>&1; then
        echo "Ошибка. Образ контейнера '${container_name}' не найден"
        return 1
    fi

    # Проверка способа запуска (вручную из терминала или через systemd)
    if [ -t 0 ]; then
        # Чтение лимитов cgroupsv2 из конфига
        nspawn_file="${NSPAWN_DIR}/${container_name}.nspawn"
        properties=$(awk '/^X-(MemoryMax|CPUQuota|TasksMax)=/ {sub(/^X-/, ""); printf "%s ", $0}' "${nspawn_file}")
        if [ -n "$properties" ]; then
            echo "Применение лимитов ${properties}"
            # Завись лимитов во временный оверрайд юнита
            sudo systemctl set-property "nsbox@${container_name}.service" ${properties}
        fi

        echo "Запуск контейнера '${container_name}' инициирован, для вывода логов выполни 'nsbox log ${container_name}'"
        # Флаг --no-block освобождает консоль
        systemctl start --no-block "nsbox@${container_name}.service"
        exit 0
    fi

    # Следуюшие команды выполняются только при запуске 'nsbox start %i' из юнита
    LOWER="${STORAGE_DIR}/${container_name}/lower"
    UPPER="${STORAGE_DIR}/${container_name}/upper"
    WORK="${STORAGE_DIR}/${container_name}/work"
    MERGED="${MACHINES_DIR}/${container_name}"
    
    umount -l "$MERGED" 2>/dev/null || true
    # Если каталог контейнера пустой, собираем в него оверлей
    if ! find "$MERGED" -mindepth 1 -print -quit | grep -q .; then
        # Размонтирование и очистка на случай старта после нештатной остановки
        umount -l "$LOWER" 2>/dev/null || true
        find "$WORK" -mindepth 1 -delete 2>/dev/null || true
        mkdir -p "$LOWER" "$UPPER" "$WORK"

        echo "Монтирование корня хоста в $LOWER"
        mount --bind -o ro / "$LOWER"
        mount --make-private "$LOWER"

        # Монтирование оверлея
        mount -t overlay overlay -o "lowerdir=${LOWER},upperdir=${UPPER},workdir=${WORK}" "$MERGED"

        # Изоляция machine-id и отключение монтирование дисков хоста (fstab)
        mkdir -p "${STORAGE_DIR}/${container_name}/upper/etc/systemd/system"
        cp /dev/null "${STORAGE_DIR}/${container_name}/upper/etc/machine-id"
        cp /dev/null "${STORAGE_DIR}/${container_name}/upper/etc/fstab"
        
        # Установка basic.target дефолтным юнитом контейнера по умолчанию
        ln -sf /usr/lib/systemd/system/basic.target \
        "${STORAGE_DIR}/${container_name}/upper/etc/systemd/system/default.target"
        
        # Отключение попытки перемонтирования корня контейнером
        ln -sf /dev/null "${STORAGE_DIR}/${container_name}/upper/etc/systemd/system/systemd-remount-fs.service" || true
    fi

    echo "Запуск контейнера '${container_name}'..."
    # Передача управления контейнеру (systemd контролирует systemd-nspawn)
    # --settings=trusted необходима, так как конфиг не в /etc/systemd/nspawn
    # --keep-unit не использовать, иначе корректно не остановить контейнер!!
    exec /usr/bin/systemd-nspawn \
        --quiet \
        --settings=trusted \
        --machine="$container_name" \
        --uuid="$(cat /proc/sys/kernel/random/uuid)" \
        -D "${MACHINES_DIR}/${container_name}"
}

stop() {
    # Проверка способа запуска (вручную из терминала или через systemd)
    if [ -t 0 ]; then
        # Следующие команды выполняются при запуске nsbox из терминала
        if ! machinectl show "$container_name" >/dev/null 2>&1; then
            echo "Контейнер '$container_name' не запущен."
            return 0
        fi

        # Отправка сигнала SIGTERM лидеру контейнера
        machinectl kill --kill-who=leader --signal=SIGTERM "$container_name"

        # Флаг --no-block возвращает управление в терминал
        systemctl stop --no-block "nsbox@${container_name}.service"
        # Сброс рантайм-конфигурации службы (для очистки лимитов cgroups2)
        systemctl revert "nsbox@${container_name}.service"
        echo "Останов контейнера '${container_name}' инициирован, для вывода логов выполни 'nsbox log ${container_name}'"
        exit 0 
    fi

    # Следуюшие команды выполняются при запуске 'nsbox stop %i' из юнита
    echo "Очистка ресурсов контейнера '${container_name}'..."

    # Если каталог контейнера это оверлей, размонтировать его
    MERGED="${MACHINES_DIR}/${container_name}"
    fs_type=$(stat -f -c %T "$MERGED" 2>/dev/null)
    echo "Размонтирование оверлея ${MERGED}"
    if [ "$fs_type" = "overlayfs" ] || [ "$fs_type" = "overlay" ]; then
        LOWER="${STORAGE_DIR}/${container_name}/lower"
        WORK="${STORAGE_DIR}/${container_name}/work"

        # Размонтирование и очистка рабочих директорий
        umount -l "$MERGED" 2>/dev/null || true
        umount -l "$LOWER" 2>/dev/null || true
        find "$WORK" -mindepth 1 -delete 2>/dev/null || true
    fi

    echo "Готово."
}

restart() {
    echo "Перезапуск контейнера '${container_name}'..."
    systemctl restart "nsbox@${container_name}.service"
    echo "Готово."
}

execute() {
    shift

    # Получение PID главного процесса контейнера через machinectl
    pid=$(machinectl show "$container_name" -p Leader --value 2>/dev/null || true)

    if [ -z "$pid" ] || [ "$pid" -eq 0 ]; then
        echo "Ошибка: Контейнер '${container_name}' не запущен или не найден PID главного процесса." >&2
        exit 1
    fi

    # Если команда не передана, запуск /bin/sh в режиме шелла входа (-l, login shell)
    if [ $# -eq 0 ]; then set -- /bin/sh -l; fi

    # Установка DISPLAY и XAUTHORITY нужна только для запуска графических приложений
    exec sudo nsenter --target "$pid" --mount --uts --ipc --net --pid -- \
        env -i \
        TERM="${TERM:-xterm-256color}" \
        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
        HOME="/root" \
        LANG="${LANG:-en_US.UTF-8}" \
        DISPLAY=":0" \
        XAUTHORITY="/run/.Xauthority" \
        "$@"
}

remove() {
    # Проверить и убрать, т.к. работающий контейнер не даст удалить machinectl remove!
    if machinectl show "$container_name" >/dev/null 2>&1; then
        echo "Ошибка: Контейнер '${container_name}' запущен, остановите перед удалением." >&2
        exit 1
    fi

    printf "Удалить контейнер '${container_name}'? [y/N] "
    read -r response
    if [ "$response" != "y" ] && [ "$response" != "Y" ]; then
        exit 0
    fi

    # Удаление каталога с образом контейнера с помощью machinectl, чтобы мог выполнять пользователь группы nsbox,
    # каталог ${STORAGE_DIR}/${container_name} пытаемся удалить только после успешного удаления образа контейнера!
    machinectl remove "$container_name" && rm -rfv "${STORAGE_DIR}/${container_name}"
    rm -f "${NSPAWN_DIR}/${container_name}.nspawn"

    # Стирание памяти systemd, если контейнер завершился с ошибкой
    systemctl reset-failed "nsbox@${container_name}.service" 2>/dev/null || true

    echo "Готово."
}

status() {
    if machinectl show "$container_name" >/dev/null 2>&1; then
        systemctl status "nsbox@${container_name}.service" --no-pager -n 0 || true
        echo ""

        machinectl --no-pager status ${container_name}
        echo "          Limits:"
        # Показать лимиты, выровненные по горизонтали как вывод machinectl
        systemctl show "nsbox@${container_name}.service" -p MemoryMax -p TasksMax -p CPUQuotaPerSecUSec | sed "s/^/$(printf '%18s')/"
    else
        echo "Контейнер '${container_name}' не зарегистрирован или выключен"
        systemctl status "nsbox@${container_name}.service" --no-pager -n 0 || true
    fi
}

log() {
    journalctl -u nsbox@${container_name} --no-pager
}

config() {
    ${EDITOR:-nano} "${NSPAWN_DIR}/${container_name}.nspawn"
}

# Проверка минимального количества аргументов
[ $# -lt 1 ] && usage

ACTION="$1"
shift
# Синонимы команд
[ "$ACTION" = "exec" ] && ACTION="execute"
[ "$ACTION" = "--help" ] && ACTION="usage"

case "$ACTION" in
    images|load|create|save|list|start|restart|stop|execute|remove|status|log|config|usage) ;;
    *)
        echo "Ошибка: неизвестная команда '$ACTION'" >&2
        usage ;;
esac

# Проверка наличия имени контейнера для всех команд, кроме list и images
if [ "$ACTION" != "list" ] && [ "$ACTION" != "images" ] && [ $# -lt 1 ]; then
    usage
fi

# Чтение имени контейнера (если указано)
container_name="${1:-}"

"$ACTION" "$@"
