#!/bin/sh

set -eu

SERVICE_TEMPLATE="nsbox@"        # Шаблон systemd-юнита
STORAGE_ROOT=/var/lib/nsbox      # Хранилище с развернутыми образами оверлеев 
MACHINES_ROOT=/var/lib/machines  # Стандартный путь machinectl

# Перезапуск от root, если скрипт запущен от обычного пользователя
if [ "$(id -u)" -ne 0 ]; then
    exec sudo "$0" "$@"
fi

usage() {
    cat << EOF
Использование: $(basename "$0") <команда> [АРГУМЕНТЫ...]

$(basename "$0") — это легковесный инструмент для управления контейнерами systemd-nspawn 

Команды:
  images                 Вывести список образов контейнеров
  list                   Вывести список запущенных контейнеров и юнитов
  load  <image[:tag]>    Загрузить образ контейнера с dockerhub
  start <container>      Запустить контейнер
  stop  <container>      Остановить контейнер
  restart <container>    Перезапустить контейнер
  exec <container> [cmd] Выполнить cmd в контейнере (по умолчанию /bin/sh)
  status <container>     Вывести статус контейнера и юнита
  log <container>        Вывести логи службы контейнера
  config <container>     Открыть файл конфигурации контейнера
  destroy <container>    Уничтожить образ контейнера
  --help                 Показать эту справку и выйти
EOF
    exit 1
}

images() {
    find "${MACHINES_ROOT}" "${STORAGE_ROOT}" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;
}

list() {
    machinectl --full list 2>/dev/null
    echo ""
    # Если не нужно выводить легенду, добавить --no-legend
    systemctl list-units "${SERVICE_TEMPLATE}*" --all --no-pager
}

load() {
    # Разбиение имени образа по двоеточию на имя и тег (если указан)
    IFS=':' read -r image tag <<< "$container_name"
    tag="${tag:-latest}"

    temp_dir="/var/tmp/${image}_${tag}"
    root_dir="${MACHINES_ROOT}/${image}"

    if [ -d "$root_dir" ]; then
        read -p "Каталог $root_dir существует, распаковать поверх? [y/N]: " response
        [[ "$response" != [yY] ]] && exit 0
    fi

    skopeo --insecure-policy copy docker://"${image}:${tag}" oci:"${temp_dir}:${tag}" &&
    umoci raw unpack --image "${temp_dir}:${tag}" "${root_dir}" && rm -rf "${temp_dir}"
}

start() {
    # Проверка запущен ли контейнер
    if machinectl show "${container_name}" >/dev/null 2>&1; then
        echo "Контейнер '${container_name}' уже запущен."
        return 0
    fi

    NSPAWN_CONF="/etc/systemd/nspawn/${container_name}.nspawn"
    echo "Создание файла конфигурации $NSPAWN_CONF"
    mkdir -p /etc/systemd/nspawn
    cp -n /etc/systemd/nspawn/config.tmpl "${NSPAWN_CONF}" 2>/dev/null || true

    # Проверка способа запуска (вручную из терминала или через systemd)
    if [ -t 0 ]; then
        # Чтение лимитов cgroupsv2 из конфига
        properties="$(grep -E '^X-(MemoryMax|CPUQuota|TasksMax)=' "${NSPAWN_CONF}" | sed 's/^X-//' | tr '\n' ' ')"
        if [ -n "${properties}" ]; then
            echo "Применение лимитов ${properties}"
            # Завись лимитов во временный оверрайд юнита
            sudo systemctl set-property "nsbox@${container_name}.service" ${properties}
        fi

        echo "Запрос на запуск контейнера '${container_name}' отправлен, смотри логи nsbox log ${container_name}"        
        # Флаг --no-block освобождает консоль
        systemctl start --no-block "nsbox@${container_name}.service"
        exit 0
    fi

    # Следуюшие команды выполняются только при вызове usr/local/bin/nsbox start %i в юните

    # Если целевого каталога нет, подготовка каталога с оверлеем
    if [ ! -d "${MACHINES_ROOT}/${container_name}" ]; then
        LOWER="${STORAGE_ROOT}/${container_name}/lower"
        UPPER="${STORAGE_ROOT}/${container_name}/upper"
        WORK="${STORAGE_ROOT}/${container_name}/work"
        MERGED="${STORAGE_ROOT}/${container_name}/merged"

        # Размонтирование и очистка на случай старта после нештатной остановки
        umount -l "$MERGED" 2>/dev/null || true
        umount -l "$LOWER" 2>/dev/null || true
        find "$WORK" -mindepth 1 -delete 2>/dev/null || true
        mkdir -p "$LOWER" "$UPPER" "$WORK" "$MERGED"
        
        # Копирование шаблона дефолтной точки входа
        cp -n "${STORAGE_ROOT}/entrypoint.sh" "$UPPER"

        echo "Монтирование корня хоста в $LOWER"
        mount --bind -o ro / "$LOWER"
        mount --make-private "$LOWER"

        # Монтирование оверлея
        mount -t overlay overlay -o "lowerdir=${LOWER},upperdir=${UPPER},workdir=${WORK}" "$MERGED"
        ln -s "$MERGED" "${MACHINES_ROOT}/${container_name}"
    fi

    # Создание необходимых каталогов в upperdir
    mkdir -p "${STORAGE_ROOT}/${container_name}/upper/etc/systemd/system"
    # Изоляция machine-id и отключение монтирование дисков хоста (fstab)
    cp /dev/null "${STORAGE_ROOT}/${container_name}/upper/etc/machine-id"
    cp /dev/null "${STORAGE_ROOT}/${container_name}/upper/etc/fstab"
    
    # Установка basic.target дефолтным юнитом контейнера по умолчанию
    ln -sf /usr/lib/systemd/system/basic.target \
    "${STORAGE_ROOT}/${container_name}/upper/etc/systemd/system/default.target"
    
    # Отключение попытки перемонтирования корня контейнером
    ln -sf /dev/null "${STORAGE_ROOT}/${container_name}/upper/etc/systemd/system/systemd-remount-fs.service" || true

    echo "Запуск контейнера '${container_name}'..."
    # Передача управления контейнеру (systemd контролирует systemd-nspawn)
    # NB! Опцию --keep-unit не использовать, иначе корректно не остановить контейнер
    exec /usr/bin/systemd-nspawn \
        --quiet \
        --machine="${container_name}" \
        --uuid="$(cat /proc/sys/kernel/random/uuid)" \
        -D "${MACHINES_ROOT}/${container_name}"
}

stop() {
    # Проверка способа запуска (вручную из терминала или через systemd)
    if [ -t 0 ]; then
        # Проверка запущен ли контейнер
        if ! machinectl show "${container_name}" >/dev/null 2>&1; then
            echo "Контейнер '${container_name}' не запущен."
            return 0
        fi

        # Отправка сигнала SIGTERM лидеру контейнера (для вызова в entrypoint.sh функции on_close)
        machinectl kill --kill-who=leader --signal=SIGTERM "${container_name}"

        echo "Запрос на останов контейнера '${container_name}' отправлен, смотри логи nsbox log ${container_name}"
        # Флаг --no-block возвращает управление в терминал
        systemctl stop --no-block "nsbox@${container_name}.service"
        exit 0 
    fi

    # Следуюшие команды выполняются только при вызове usr/local/bin/nsbox stop %i в юните 
    echo "Очистка ресурсов контейнера '${container_name}'..."

    # Очистка оверлея, если в MACHINES_ROOT каталог контейнера это симлинк на STORAGE_ROOT
    if [ -L "${MACHINES_ROOT}/${container_name}" ]; then
        LOWER="${STORAGE_ROOT}/${container_name}/lower"
        UPPER="${STORAGE_ROOT}/${container_name}/upper"
        WORK="${STORAGE_ROOT}/${container_name}/work"
        MERGED="${STORAGE_ROOT}/${container_name}/merged"

        # Размонтирование и очистка рабочих директорий
        umount -l "$MERGED" 2>/dev/null || true
        umount -l "$LOWER" 2>/dev/null || true
        find "$WORK" -mindepth 1 -delete 2>/dev/null || true

        rm "${MACHINES_ROOT}/${container_name}"
    fi

    echo "Готово."
}

restart() {
    echo "Перезапуск контейнера '${container_name}'..."
    systemctl restart "${SERVICE_TEMPLATE}${container_name}.service"
    echo "Готово."
}

execute() {
    shift

    # Получение PID главного процесса контейнера через machinectl
    pid=$(machinectl show "$container_name" -p Leader --value 2>/dev/null || true)

    if [ -z "$pid" ] || [ "$pid" -eq 0 ]; then
        echo "Ошибка: Контейнер '${container_name}' не запущен или не найден PID главного процесса." >&2
        exit 1
    fi

    # Если команда не передана, запуск /bin/sh в режиме шелла входа (-l, login shell)
    if [ $# -eq 0 ]; then set -- /bin/sh -l; fi

    # Установка DISPLAY и XAUTHORITY нужна только для запуска графических приложений
    exec nsenter --target "$pid" --mount --uts --ipc --net --pid -- \
        env -i \
        TERM="${TERM:-xterm-256color}" \
        PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
        HOME="/root" \
        LANG="${LANG:-en_US.UTF-8}" \
        DISPLAY=":0" \
        XAUTHORITY="/run/.Xauthority" \
        "$@"
}

destroy() {
    if machinectl show "${container_name}" >/dev/null 2>&1; then
        echo "Ошибка: Контейнер '${container_name}' запущен, остановите перед удалением." >&2
        exit 1
    fi

    printf "Удалить контейнер '${container_name}'? [y/N] "
    read -r response
    if [ "$response" != "y" ] && [ "$response" != "Y" ]; then
        exit 0
    fi

    # Чтобы обезопасить удаление преобразуем container_name через systemd-escape, 
    # если содержит спецсимволы, слэши или точки, вернет код ошибки
    systemd-escape --mangle "${container_name}" >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        exit 1
    fi

    # Удаление каталогов контейнера, если существуют
    rm -rfv "${MACHINES_ROOT}/${container_name}"
    rm -rfv "${STORAGE_ROOT}/${container_name}"

    # Удаление файла конфигурации, если существует
    rm -fv /etc/systemd/nspawn/${container_name}.nspawn

    echo "Готово."
}

status() {
    if machinectl show "${container_name}" >/dev/null 2>&1; then
        systemctl status "${SERVICE_TEMPLATE}${container_name}.service" --no-pager -n 0 || true
        echo ""

        machinectl --no-pager status ${container_name}
        echo "          Limits:"
        # Показать лимиты, выровненные по горизонтали как вывод machinectl
        systemctl show nsbox@"${container_name}".service -p MemoryMax -p TasksMax -p CPUQuotaPerSecUSec | sed "s/^/$(printf '%18s')/"
    else
        echo "Контейнер '${container_name}' не зарегистрирован или выключен"
        systemctl status "${SERVICE_TEMPLATE}${container_name}.service" --no-pager -n 0 || true
    fi
}

log() {
    journalctl -u nsbox@${container_name} --no-pager
}

config() {
    ${EDITOR:-nano} /etc/systemd/nspawn/${container_name}.nspawn
}

# Проверка минимального количества аргументов
[ $# -lt 1 ] && usage

ACTION="$1"
shift
# Синонимы команд
[ "$ACTION" = "exec" ] && ACTION="execute"
[ "$ACTION" = "--help" ] && ACTION="usage"

case "$ACTION" in
    images|load|list|start|restart|stop|execute|destroy|status|log|config|usage) ;;
    *)
        echo "Ошибка: неизвестная команда '$ACTION'" >&2
        usage ;;
esac

# Проверка наличия имени контейнера для всех команд, кроме list и images
if [ "$ACTION" != "list" ] && [ "$ACTION" != "images" ] && [ $# -lt 1 ]; then
    usage
fi

# Чтение имени контейнера (если указано)
container_name="${1:-}"

"$ACTION" "$@"
