# /etc/nftables.d/nspawn-nat.conf

# Добавляем статичный NAT для подсети контейнеров
table ip nat {
    chain POSTROUTING {
        type nat hook postrouting priority srcnat; policy accept;
        ip saddr 192.168.100.0/24 masquerade
    }
}

# Разрешаем прохождение трафика мимо блокировок Docker/Libvirt
table ip filter {
    chain FORWARD {
        type filter hook forward priority filter; policy accept;
        iifname "ve-*" accept
        oifname "ve-*" ct state established,related accept
    }
}
